"""GUI definitions."""
# Python standard libraries
from matplotlib.widgets import Cursor
import datetime
import os
import sys

# Third party libraries
from PyQt5.QtWidgets import QApplication, QMainWindow, QVBoxLayout, QLineEdit, \
    QComboBox, QSystemTrayIcon
from PyQt5 import uic, QtCore, QtGui
from PyQt5.QtGui import QIcon, QDoubleValidator

# Local libraries
from transistordatabase.database_manager import DatabaseManager
from transistordatabase.checker_functions import csv2array
from transistordatabase.gui._utils import resource_path
from transistordatabase.gui._widgets import MatplotlibWidget, EmittingStream, PopOutPlotWindow, ViewCurveWindow  # noqa: F401
from transistordatabase.gui.mixins import (
    UtilitiesMixin,
    SettingsMixin,
    ExportToolsMixin,
    TransistorCreationMixin,
    SearchDatabaseMixin,
    CurveManagementMixin,
    ComparisonToolsMixin,
    TopologyCalculatorMixin,
)


class MainWindow(
    QMainWindow,
    UtilitiesMixin,
    SettingsMixin,
    SearchDatabaseMixin,
    TransistorCreationMixin,
    CurveManagementMixin,
    ExportToolsMixin,
    ComparisonToolsMixin,
    TopologyCalculatorMixin,
):
    """
    MainWindow class which inherits from QMainWindow.

    Contains all the code and functions to implement all functionalities into the code generated by QTDesigner in MainWindow.ui
    """

    tdb: DatabaseManager

    def __init__(self):
        super(MainWindow, self).__init__()

        MainWindow_path = os.path.join(os.path.dirname(__file__), "MainWindow.ui")
        uic.loadUi(MainWindow_path, self)

        sys.stdout = EmittingStream(text_written=self.standard_output_written)

        self.tray_icon = QSystemTrayIcon(QIcon(resource_path("window_icon.png")), parent=app)
        self.tray_icon.setToolTip("Transistordatabase")
        self.tray_icon.show()
        self.tray_icon.activated.connect(self.show)

        self.setWindowTitle("Transistordatabase")

        self.tdb = DatabaseManager()
        self.tdb.set_operation_mode_json(os.path.join(os.path.dirname(__file__), "..", "database"))

        transistor_list = self.tdb.get_transistor_names_list()

        self.setWindowIcon(QtGui.QIcon("window_icon"))

        self.translation_dict = {
            'IEC 60747-9': 'IEC 60747-9 (MOSFET)',
            'IEC 60747-8': 'IEC 60747-8 (IGBT)',
            'Mitsubishi': 'Mitsubishi',
            'Infineon': 'Infineon',
            'Wolfspeed': 'Wolfspeed',

        }

        self.action_save_settings.triggered.connect(self.save_settings)
        self.action_export_settings.triggered.connect(self.export_settings)
        self.action_load_settings.triggered.connect(self.load_settings)
        self.action_stdout.triggered.connect(self.show_stdout)
        self.action_clear_comparison_tools.triggered.connect(self.clear_comparison_tools)
        self.action_clear_topology_calculator.triggered.connect(self.clear_topology_calculator)
        self.action_clear_create_transistor.triggered.connect(self.clear_create_transistor)
        self.action_exit.triggered.connect(app.exit)

        # Actions for 'Transistor' #
        self.action_delete_transistor.triggered.connect(self.delete_marked_transistor_search_database_from_local_tdb)
        self.action_show_original_datasheet.triggered.connect(self.webbrowser_original_datasheet)
        self.action_show_virtual_datasheet.triggered.connect(self.webbrowser_virtual_datasheet)
        self.action_add_transistor_to_transistordatabase_file_exchange.triggered.connect(
            self.email_add_transistor_to_transistordatabase_file_exchange)

        # Actions for 'help' #
        self.action_contribute.triggered.connect(self.webbrowser_contribute)
        self.action_documentation.triggered.connect(self.webbrowser_documentation)
        self.action_report_bug.triggered.connect(self.webbrowser_bugreport)

        # TOPOLOGY CALCULATOR #

        # create the six Matplotlib figures needed
        self.matplotlibwidget_topology1 = MatplotlibWidget()
        self.matplotlibwidget_topology2 = MatplotlibWidget()
        self.matplotlibwidget_topology3 = MatplotlibWidget()
        self.matplotlibwidget_topology4 = MatplotlibWidget()
        self.matplotlibwidget_topology5 = MatplotlibWidget()
        self.matplotlibwidget_topology6 = MatplotlibWidget()

        # fill all ComboBoxes when starting the program

        items_comboBox_topology_topology = ["Buck-Converter", "Boost-Converter", "Buck-Boost-Converter"]
        self.comboBox_topology_topology.addItems(items_comboBox_topology_topology)
        self.comboBox_topology_transistor1.addItems(transistor_list)
        self.comboBox_topology_transistor2.addItems(transistor_list)

        items_comboBox_line_contour = ["Contour", "Line"]
        self.comboBox_topology_plot1_line_contour.addItems(items_comboBox_line_contour)
        self.comboBox_topology_plot2_line_contour.addItems(items_comboBox_line_contour)
        self.comboBox_topology_plot3_line_contour.addItems(items_comboBox_line_contour)
        self.comboBox_topology_plot4_line_contour.addItems(items_comboBox_line_contour)
        self.comboBox_topology_plot5_line_contour.addItems(items_comboBox_line_contour)
        self.comboBox_topology_plot6_line_contour.addItems(items_comboBox_line_contour)

        items_comboBox_topology_x_axis = ["Vin [V]", "Vout [V]", "Output Power [W]", "Frequency [kHz]", "Zeta = f*L"]
        items_comboBox_topology_y_axis = ["Vin [V]", "Vout [V]", "Output Power [W]", "Frequency [kHz]", "Zeta = f*L"]
        items_comboBox_topology_z_axis = ["RMS Current Transistor1 [A]",
                                          "RMS Current Diode Transistor2 [A]",
                                          "Mean Current Transistor1 [A]",
                                          "Mean Current Diode Transistor2 [A]",
                                          "RMS Inductor Current [A]",
                                          "Mean Inductor Current [A]",
                                          "Peak Current [A]",
                                          "Conduction Losses Transistor1 [W]",
                                          "Conduction Losses Diode Transistor2 [W]",
                                          "Total Conduction Losses [W]",
                                          "Turn-on Switching Losses Transistor1 [W]",
                                          "Turn-off Switching Losses Transistor1 [W]",
                                          "Reverse Recovery Losses Diode Transistor2 [W]",
                                          "Total Switching Losses Transistor1 [W]",
                                          "Total Power Losses Transistor1 [W]",
                                          "Total Switching Losses [W]",
                                          "Temperature Switch Transistor1 [°C]",
                                          "Temperature Diode Transistor2 [°C]"]

        self.comboBox_topology_plot1_x_axis.addItems(items_comboBox_topology_x_axis)
        self.comboBox_topology_plot1_y_axis.addItems(items_comboBox_topology_y_axis)
        self.comboBox_topology_plot1_z_axis.addItems(items_comboBox_topology_z_axis)

        self.comboBox_topology_plot2_x_axis.addItems(items_comboBox_topology_x_axis)
        self.comboBox_topology_plot2_y_axis.addItems(items_comboBox_topology_y_axis)
        self.comboBox_topology_plot2_z_axis.addItems(items_comboBox_topology_z_axis)

        self.comboBox_topology_plot3_x_axis.addItems(items_comboBox_topology_x_axis)
        self.comboBox_topology_plot3_y_axis.addItems(items_comboBox_topology_y_axis)
        self.comboBox_topology_plot3_z_axis.addItems(items_comboBox_topology_z_axis)

        self.comboBox_topology_plot4_x_axis.addItems(items_comboBox_topology_x_axis)
        self.comboBox_topology_plot4_y_axis.addItems(items_comboBox_topology_y_axis)
        self.comboBox_topology_plot4_z_axis.addItems(items_comboBox_topology_z_axis)

        self.comboBox_topology_plot5_x_axis.addItems(items_comboBox_topology_x_axis)
        self.comboBox_topology_plot5_y_axis.addItems(items_comboBox_topology_y_axis)
        self.comboBox_topology_plot5_z_axis.addItems(items_comboBox_topology_z_axis)

        self.comboBox_topology_plot6_x_axis.addItems(items_comboBox_topology_x_axis)
        self.comboBox_topology_plot6_y_axis.addItems(items_comboBox_topology_y_axis)
        self.comboBox_topology_plot6_z_axis.addItems(items_comboBox_topology_z_axis)

        # connect the update button with the function to update the plots
        self.button_topology_update_plots.clicked.connect(self.topology_update_plots)

        # connect the buttons to pop-out plots with the function to pop-out the plot
        self.button_topology_pop_out_plot1.clicked.connect(self.topology_pop_out_plot1)
        self.button_topology_pop_out_plot2.clicked.connect(self.topology_pop_out_plot2)
        self.button_topology_pop_out_plot3.clicked.connect(self.topology_pop_out_plot3)
        self.button_topology_pop_out_plot4.clicked.connect(self.topology_pop_out_plot4)
        self.button_topology_pop_out_plot5.clicked.connect(self.topology_pop_out_plot5)
        self.button_topology_pop_out_plot6.clicked.connect(self.topology_pop_out_plot6)

        # run the functions "comboBox_topology_transistor1_changed" and "comboBox_topology_transistor2_changed",
        # when the current text of the ComboBoxes to choose the transistors changed, which will reset and refill
        # the ComboBoxes that store transistor specific selections(gate-voltages and gate-resistors)

        self.start = True
        self.comboBox_topology_transistor1.currentTextChanged.connect(self.comboBox_topology_transistor1_changed)
        self.comboBox_topology_transistor1_changed()

        # run the function "slider_topology_r_g_value_changed" when a slider to choose the gate resistor changed,
        # which will then change the Text of the Label below to show current selection
        self.slider_topology_r_g_on_transistor1.valueChanged.connect(self.slider_topology_r_g_value_changed)
        self.slider_topology_r_g_off_transistor1.valueChanged.connect(self.slider_topology_r_g_value_changed)

        # run the function "comboBox_topology_topology_changed" when the current text of the ComboBox to choose the
        # topology changed, which will set the picture of the the circuit diagram below for chosen topology
        self.comboBox_topology_topology.currentTextChanged.connect(self.comboBox_topology_topology_changed)
        self.comboBox_topology_topology_changed()

        # run the function "comboBox_topology_plots_line_contour_changed", when the current text of a ComboBox to choose
        # if a plot should be in line or contour
        self.comboBox_topology_plot1_line_contour.currentTextChanged.connect(
            self.comboBox_topology_plots_line_contour_changed)
        self.comboBox_topology_plot2_line_contour.currentTextChanged.connect(
            self.comboBox_topology_plots_line_contour_changed)
        self.comboBox_topology_plot3_line_contour.currentTextChanged.connect(
            self.comboBox_topology_plots_line_contour_changed)
        self.comboBox_topology_plot3_line_contour.currentTextChanged.connect(
            self.comboBox_topology_plots_line_contour_changed)
        self.comboBox_topology_plot4_line_contour.currentTextChanged.connect(
            self.comboBox_topology_plots_line_contour_changed)
        self.comboBox_topology_plot5_line_contour.currentTextChanged.connect(
            self.comboBox_topology_plots_line_contour_changed)
        self.comboBox_topology_plot6_line_contour.currentTextChanged.connect(
            self.comboBox_topology_plots_line_contour_changed)

        # run the function "comboBox_topology_plots_x_axis_changed", when the current text of a CombBox to choose
        # the variable for the x-axis changed
        self.comboBox_topology_plot1_x_axis.currentTextChanged.connect(self.comboBox_topology_plots_x_axis_changed)
        self.comboBox_topology_plot2_x_axis.currentTextChanged.connect(self.comboBox_topology_plots_x_axis_changed)
        self.comboBox_topology_plot3_x_axis.currentTextChanged.connect(self.comboBox_topology_plots_x_axis_changed)
        self.comboBox_topology_plot3_x_axis.currentTextChanged.connect(self.comboBox_topology_plots_x_axis_changed)
        self.comboBox_topology_plot4_x_axis.currentTextChanged.connect(self.comboBox_topology_plots_x_axis_changed)
        self.comboBox_topology_plot5_x_axis.currentTextChanged.connect(self.comboBox_topology_plots_x_axis_changed)
        self.comboBox_topology_plot6_x_axis.currentTextChanged.connect(self.comboBox_topology_plots_x_axis_changed)

        # Topology Calculator: set input masks and validators
        self.lineEdit_topology_output_power.setValidator(QDoubleValidator())
        self.lineEdit_topology_v_in.setValidator(QDoubleValidator())
        self.lineEdit_topology_v_out.setValidator(QDoubleValidator())
        self.lineEdit_topology_frequency.setValidator(QDoubleValidator())
        self.lineEdit_topology_zeta.setValidator(QDoubleValidator())
        self.lineEdit_topology_temperature_heatsink.setValidator(QDoubleValidator())
        self.lineEdit_topology_thermal_resistance_heatsink.setValidator(QDoubleValidator())
        self.lineEdit_topology_number_parallel_transistor1.setValidator(QDoubleValidator())
        self.lineEdit_topology_output_power_min.setValidator(QDoubleValidator())
        self.lineEdit_topology_v_in_min.setValidator(QDoubleValidator())
        self.lineEdit_topology_v_out_min.setValidator(QDoubleValidator())
        self.lineEdit_topology_frequency_min.setValidator(QDoubleValidator())
        self.lineEdit_topology_zeta_min.setValidator(QDoubleValidator())
        self.lineEdit_topology_number_parallel_transistor2.setValidator(QDoubleValidator())
        self.lineEdit_topology_output_power_max.setValidator(QDoubleValidator())
        self.lineEdit_topology_v_in_max.setValidator(QDoubleValidator())
        self.lineEdit_topology_v_out_max.setValidator(QDoubleValidator())
        self.lineEdit_topology_frequency_max.setValidator(QDoubleValidator())
        self.lineEdit_topology_zeta_max.setValidator(QDoubleValidator())

        # COMPARISON TOOLS #

        self.comboBox_compare_transistor1.setStyleSheet("color: blue")
        self.comboBox_compare_transistor2.setStyleSheet("color: green")
        self.comboBox_compare_transistor3.setStyleSheet("color: red")

        # fill the comboBoxes to choose transistors
        self.comboBox_compare_transistor1.addItems(transistor_list)
        self.comboBox_compare_transistor2.addItems(transistor_list)
        self.comboBox_compare_transistor3.addItems(transistor_list)

        # connect the button to update the plots with the function to update the plots
        self.button_compare_update_plots.clicked.connect(self.compare_update_plots)

        # connect the buttons to pop-out plots with the function to pop-out the plot
        self.button_compare_pop_out_plot1.clicked.connect(self.compare_pop_out_plot1)
        self.button_compare_pop_out_plot2.clicked.connect(self.compare_pop_out_plot2)
        self.button_compare_pop_out_plot3.clicked.connect(self.compare_pop_out_plot3)
        self.button_compare_pop_out_plot4.clicked.connect(self.compare_pop_out_plot4)
        self.button_compare_pop_out_plot5.clicked.connect(self.compare_pop_out_plot5)
        self.button_compare_pop_out_plot6.clicked.connect(self.compare_pop_out_plot6)
        self.button_compare_pop_out_plot7.clicked.connect(self.compare_pop_out_plot7)
        self.button_compare_pop_out_plot8.clicked.connect(self.compare_pop_out_plot8)
        self.button_compare_pop_out_plot9.clicked.connect(self.compare_pop_out_plot9)

        # fill the comboBoxes to select the data to plot
        items_comboBoxes_compare = ["Switch Channel Data",
                                    "Diode Channel Data",
                                    "Switch Turn-on Losses",
                                    "Switch Turn-off Losses",
                                    "Diode Reverse Recovery Losses",
                                    "Output Capacitance Charge vs. Channel Voltage",
                                    "Output Capacitance Energy vs. Channel Voltage",
                                    "Switch Energy Data vs. Channel Current Transistor1",
                                    "Diode Energy Data vs. Channel Current Transistor1",
                                    "Switch Energy Data vs. Gate Resistor Transistor1",
                                    "Diode Energy Data vs. Gate Resistor Transistor1",
                                    "Switch Energy Data vs. Channel Current Transistor2",
                                    "Diode Energy Data vs. Channel Current Transistor2",
                                    "Switch Energy Data vs. Gate Resistor Transistor2",
                                    "Diode Energy Data vs. Gate Resistor Transistor2",
                                    "Switch Energy Data vs. Channel Current Transistor3",
                                    "Diode Energy Data vs. Channel Current Transistor3",
                                    "Switch Energy Data vs. Gate Resistor Transistor3",
                                    "Diode Energy Data vs. Gate Resistor Transistor3",
                                    "Switch Channel Data Transistor1",
                                    "Diode Channel Data Transistor1",
                                    "Switch Channel Data Transistor2",
                                    "Diode Channel Data Transistor2",
                                    "Switch Channel Data Transistor3",
                                    "Diode Channel Data Transistor3"]

        self.comboBox_compare_plot1.addItems(items_comboBoxes_compare)
        self.comboBox_compare_plot2.addItems(items_comboBoxes_compare)
        self.comboBox_compare_plot3.addItems(items_comboBoxes_compare)
        self.comboBox_compare_plot4.addItems(items_comboBoxes_compare)
        self.comboBox_compare_plot5.addItems(items_comboBoxes_compare)
        self.comboBox_compare_plot6.addItems(items_comboBoxes_compare)
        self.comboBox_compare_plot7.addItems(items_comboBoxes_compare)
        self.comboBox_compare_plot8.addItems(items_comboBoxes_compare)
        self.comboBox_compare_plot9.addItems(items_comboBoxes_compare)

        # Create the nine Matplotlib figures needed
        self.matplotlibwidget_compare1 = MatplotlibWidget()
        self.matplotlibwidget_compare2 = MatplotlibWidget()
        self.matplotlibwidget_compare3 = MatplotlibWidget()
        self.matplotlibwidget_compare4 = MatplotlibWidget()
        self.matplotlibwidget_compare5 = MatplotlibWidget()
        self.matplotlibwidget_compare6 = MatplotlibWidget()
        self.matplotlibwidget_compare7 = MatplotlibWidget()
        self.matplotlibwidget_compare8 = MatplotlibWidget()
        self.matplotlibwidget_compare9 = MatplotlibWidget()

        # run the function "slider_topology_r_g_value_changed" when a slider to choose the gate resistor changed,
        # which will then change the Text of the Label below to show current selection
        self.slider_compare_r_g_on_transistor1.valueChanged.connect(self.slider_compare_r_g_value_changed)
        self.slider_compare_r_g_off_transistor1.valueChanged.connect(self.slider_compare_r_g_value_changed)
        self.slider_compare_r_g_on_transistor2.valueChanged.connect(self.slider_compare_r_g_value_changed)
        self.slider_compare_r_g_off_transistor2.valueChanged.connect(self.slider_compare_r_g_value_changed)
        self.slider_compare_r_g_on_transistor3.valueChanged.connect(self.slider_compare_r_g_value_changed)
        self.slider_compare_r_g_off_transistor3.valueChanged.connect(self.slider_compare_r_g_value_changed)

        # run the function "comboBox_compare_transistors_changed", when the current text of a comboBox to choose the
        # transistors changed
        self.comboBox_compare_transistor1.currentTextChanged.connect(self.comboBox_compare_transistor1_changed)
        self.comboBox_compare_transistor2.currentTextChanged.connect(self.comboBox_compare_transistor2_changed)
        self.comboBox_compare_transistor3.currentTextChanged.connect(self.comboBox_compare_transistor3_changed)
        self.comboBox_compare_transistor1_changed()
        self.comboBox_compare_transistor2_changed()
        self.comboBox_compare_transistor3_changed()

        # Comparison Tools: set input masks and validators
        self.lineEdit_compare_t_j_transistor1.setValidator(QDoubleValidator())
        self.lineEdit_compare_t_j_transistor2.setValidator(QDoubleValidator())
        self.lineEdit_compare_t_j_transistor3.setValidator(QDoubleValidator())
        self.lineEdit_compare_v_supply_transistor1.setValidator(QDoubleValidator())
        self.lineEdit_compare_v_supply_transistor2.setValidator(QDoubleValidator())
        self.lineEdit_compare_v_supply_transistor3.setValidator(QDoubleValidator())
        self.lineEdit_compare_number_parallel_transistor1.setValidator(QDoubleValidator())
        self.lineEdit_compare_number_parallel_transistor2.setValidator(QDoubleValidator())
        self.lineEdit_compare_number_parallel_transistor3.setValidator(QDoubleValidator())

        # Exporting Tools #

        # add Items to the comboBox and set standard values for parallel transistor and normalize-t-to-v value
        self.comboBox_export_transistor.addItems(transistor_list)

        # connect the buttons to the functions
        self.button_export_datasheet.clicked.connect(self.export_datasheet)
        self.button_export_json.clicked.connect(self.export_json)
        self.button_export_matlab.clicked.connect(self.export_matlab)
        self.button_export_simulink.clicked.connect(self.export_simulink)
        self.button_export_gecko.clicked.connect(self.export_gecko)
        self.button_export_plecs.clicked.connect(self.export_plecs)

        # Exporting Tools: set input masks and validators for transistor parameters
        self.lineEdit_export_number_parallel_transistors.setValidator(QDoubleValidator())
        self.lineEdit_export_simulink_v_supply.setValidator(QDoubleValidator())
        self.lineEdit_export_simulink_r_g_on.setValidator(QDoubleValidator())
        self.lineEdit_export_simulink_r_g_off.setValidator(QDoubleValidator())
        self.lineEdit_export_simulink_normalize_t_to_v.setValidator(QDoubleValidator())
        self.lineEdit_export_gecko_v_supply.setValidator(QDoubleValidator())
        self.lineEdit_export_gecko_r_g_on.setValidator(QDoubleValidator())
        self.lineEdit_export_gecko_r_g_off.setValidator(QDoubleValidator())
        self.lineEdit_export_gecko_v_g_on.setValidator(QDoubleValidator())
        self.lineEdit_export_gecko_v_g_off.setValidator(QDoubleValidator())
        self.lineEdit_export_plecs_v_g_on.setValidator(QDoubleValidator())
        self.lineEdit_export_plecs_v_g_off.setValidator(QDoubleValidator())
        self.lineEdit_export_plecs_v_d_on.setValidator(QDoubleValidator())
        self.lineEdit_export_plecs_v_d_off.setValidator(QDoubleValidator())

        # CREATE TRANSISTOR #

        self.fill_comboBoxes_create_transistor()

        for widget in self.scrollAreaWidgetContents_create_transistor.children():
            if isinstance(widget, QComboBox) or isinstance(widget, QLineEdit):
                widget.setStyleSheet("color: green")

        # connect all buttons to their specific functions
        self.button_create_transistor_switch_add_curve_channel_data.clicked.connect(self.add_curve_switch_channel)
        self.button_create_transistor_switch_delete_curve_channel_data.clicked.connect(self.delete_curve_switch_channel)

        self.button_create_transistor_switch_add_curve_switching_losses.clicked.connect(
            self.add_curve_switch_switching_losses)
        self.button_create_transistor_switch_delete_curve_switching_losses.clicked.connect(
            self.delete_curve_switch_switching_losses)

        self.button_create_transistor_switch_add_curve_gate_charge.clicked.connect(self.add_curve_switch_gate_charge)
        self.button_create_transistor_switch_delete_curve_gate_charge.clicked.connect(
            self.delete_curve_switch_gate_charge)

        self.button_create_transistor_switch_add_curve_r_on.clicked.connect(self.add_curve_switch_r_on)
        self.button_create_transistor_switch_delete_curve_r_on.clicked.connect(self.delete_curve_switch_r_on)

        self.button_create_transistor_diode_add_curve_channel_data.clicked.connect(self.add_curve_diode_channel)
        self.button_create_transistor_diode_delete_curve_channel_data.clicked.connect(self.delete_curve_diode_channel)

        self.button_create_transistor_diode_add_curve_switching_losses.clicked.connect(
            self.add_curve_diode_switching_losses)
        self.button_create_transistor_diode_delete_curve_switching_losses.clicked.connect(
            self.delete_curve_diode_switching_losses)

        self.button_create_transistor_switch_add_t_rthjc_curve.clicked.connect(self.add_curve_switch_t_rthjc)
        self.button_create_transistor_switch_delete_curve_t_rthjc.clicked.connect(self.delete_curve_switch_t_rthjc)

        self.button_create_transistor_diode_add_t_rthjc_curve.clicked.connect(self.add_curve_diode_t_rthjc)
        self.button_create_transistor_diode_delete_curve_t_rthjc.clicked.connect(self.delete_curve_diode_t_rthjc)

        self.button_create_transistor_add_curve_v_ecoss.clicked.connect(self.add_curve_v_ecoss)
        self.button_create_transistor_delete_curve_v_ecoss.clicked.connect(self.delete_curve_v_ecoss)

        self.button_create_transistor_add_curve_c_iss_normal.clicked.connect(self.add_curve_c_iss_normal)
        self.button_create_transistor_delete_curve_c_iss_normal.clicked.connect(self.delete_curve_c_iss_normal)

        self.button_create_transistor_add_curve_c_iss_detail.clicked.connect(self.add_curve_c_iss_detail)
        self.button_create_transistor_delete_curve_c_iss_detail.clicked.connect(self.delete_curve_c_iss_detail)

        self.button_create_transistor_add_curve_c_oss_normal.clicked.connect(self.add_curve_c_oss_normal)
        self.button_create_transistor_delete_curve_c_oss_normal.clicked.connect(self.delete_curve_c_oss_normal)

        self.button_create_transistor_add_curve_c_oss_detail.clicked.connect(self.add_curve_c_oss_detail)
        self.button_create_transistor_delete_curve_c_oss_detail.clicked.connect(self.delete_curve_c_oss_detail)

        self.button_create_transistor_add_curve_c_rss_normal.clicked.connect(self.add_curve_c_rss_normal)
        self.button_create_transistor_delete_curve_c_rss_normal.clicked.connect(self.delete_curve_c_rss_normal)

        self.button_create_transistor_add_curve_c_rss_detail.clicked.connect(self.add_curve_c_rss_detail)
        self.button_create_transistor_delete_curve_c_rss_detail.clicked.connect(self.delete_curve_c_rss_detail)

        self.button_create_transistor_switch_add_curve_soa_t_pulse.clicked.connect(self.add_curve_switch_soa_t_pulse)
        self.button_create_transistor_switch_delete_curve_soa_t_pulse.clicked.connect(
            self.delete_curve_switch_soa_t_pulse)

        self.button_create_transistor_diode_add_curve_soa_t_pulse.clicked.connect(self.add_curve_diode_soa_t_pulse)
        self.button_create_transistor_diode_delete_curve_soa_t_pulse.clicked.connect(
            self.delete_curve_diode_soa_t_pulse)

        self.button_create_transistor_create.clicked.connect(self.load_transistor_into_local_database)
        self.button_create_transistor_preview_transistor.clicked.connect(self.preview_transistor_on_virtual_datasheet)

        self.button_create_transistor_view_curve_switch_channel_data.clicked.connect(self.view_curve_switch_channel)
        self.button_create_transistor_view_curve_switch_switching_losses.clicked.connect(
            self.view_curve_switch_switching_losses)
        self.button_create_transistor_view_curve_switch_gate_charge.clicked.connect(self.view_curve_switch_gate_charge)
        self.button_create_transistor_view_curve_switch_r_on.clicked.connect(self.view_curve_switch_r_on)
        self.button_create_transistor_view_curve_switch_soa_t_pulse.clicked.connect(self.view_curve_switch_soa_t_pulse)
        self.button_create_transistor_view_curve_diode_channel_data.clicked.connect(self.view_curve_diode_channel)
        self.button_create_transistor_view_curve_diode_switching_losses.clicked.connect(
            self.view_curve_diode_switching_losses)
        self.button_create_transistor_view_curve_diode_soa_t_pulse.clicked.connect(self.view_curve_diode_soa_t_pulse)
        self.button_create_transistor_view_curve_switch_t_rthjc.clicked.connect(self.view_curve_switch_t_rthjc)
        self.button_create_transistor_view_curve_diode_t_rthjc.clicked.connect(self.view_curve_diode_t_rthjc)
        self.button_create_transistor_view_curve_v_ecoss.clicked.connect(self.view_curve_v_ecoss)
        self.button_create_transistor_view_curve_c_iss_normal.clicked.connect(self.view_curve_c_iss_normal)
        self.button_create_transistor_view_curve_c_iss_detail.clicked.connect(self.view_curve_c_iss_detail)
        self.button_create_transistor_view_curve_c_oss_normal.clicked.connect(self.view_curve_c_oss_normal)
        self.button_create_transistor_view_curve_c_oss_detail.clicked.connect(self.view_curve_c_oss_detail)
        self.button_create_transistor_view_curve_c_rss_normal.clicked.connect(self.view_curve_c_rss_normal)
        self.button_create_transistor_view_curve_c_rss_detail.clicked.connect(self.view_curve_c_rss_detail)

        self.button_create_transistor_add_directory_dpt.clicked.connect(self.add_dpt_measurement_data_directory)
        self.button_create_transistor_view_directory_dpt.clicked.connect(self.view_dpt_measurement_data)
        self.button_create_transistor_delete_directory_dpt.clicked.connect(self.delete_dpt_measurement_data)

        self.comboBox_create_transistor_switch_add_switching_losses_curve_type.currentTextChanged.connect(
            self.comboBox_create_transistor_switch_add_switching_losses_curve_type_changed)
        self.comboBox_create_transistor_diode_add_switching_losses_curve_type.currentTextChanged.connect(
            self.comboBox_create_transistor_diode_add_switching_losses_curve_type_changed)

        self.lineEdit_create_transistor_add_data_dpt_measurement_date.setText(str(datetime.date.today()))

        # Testbench combobox
        self.comboBox_create_transistor_add_data_dpt_measurement_testbench.addItems(['', 'Paderborn University / LEA'])
        self.comboBox_create_transistor_add_data_dpt_measurement_testbench.setEditable(True)

        # Sets all settings given in the settings.json file in the current working directory
        self.load_local_settings()

        # create transistor: set input masks and validators for transistor parameters
        self.lineEdit_create_transistor_v_abs_max.setValidator(QDoubleValidator())
        self.lineEdit_create_transistor_i_abs_max.setValidator(QDoubleValidator())
        self.lineEdit_create_transistor_i_cont.setValidator(QDoubleValidator())
        self.lineEdit_create_transistor_transistor_c_oss_er_c_o.setValidator(QDoubleValidator())
        self.lineEdit_create_transistor_transistor_c_oss_er_v_gs.setValidator(QDoubleValidator())
        self.lineEdit_create_transistor_transistor_c_oss_er_v_ds.setValidator(QDoubleValidator())
        self.lineEdit_create_transistor_transistor_c_oss_tr_c_o.setValidator(QDoubleValidator())
        self.lineEdit_create_transistor_transistor_c_oss_tr_v_gs.setValidator(QDoubleValidator())
        self.lineEdit_create_transistor_transistor_c_oss_tr_v_ds.setValidator(QDoubleValidator())
        self.lineEdit_create_transistor_t_c_max.setValidator(QDoubleValidator())
        self.lineEdit_create_transistor_r_g_int.setValidator(QDoubleValidator())
        self.lineEdit_create_transistor_r_th_cs.setValidator(QDoubleValidator())
        self.lineEdit_create_transistor_r_th_diode_cs.setValidator(QDoubleValidator())
        self.lineEdit_create_transistor_r_th_switch_cs.setValidator(QDoubleValidator())
        self.lineEdit_create_transistor_r_g_on_recommended.setValidator(QDoubleValidator())
        self.lineEdit_create_transistor_r_g_off_recommended.setValidator(QDoubleValidator())
        self.lineEdit_create_transistor_c_iss_fix.setValidator(QDoubleValidator())
        self.lineEdit_create_transistor_c_oss_fix.setValidator(QDoubleValidator())
        self.lineEdit_create_transistor_c_rss_fix.setValidator(QDoubleValidator())
        self.lineEdit_create_transistor_add_curve_c_iss_t_j.setValidator(QDoubleValidator())
        self.lineEdit_create_transistor_add_curve_c_oss_t_j.setValidator(QDoubleValidator())
        self.lineEdit_create_transistor_add_curve_c_rss_t_j.setValidator(QDoubleValidator())
        self.lineEdit_create_transistor_add_data_dpt_load_inductance.setValidator(QDoubleValidator())
        self.lineEdit_create_transistor_add_data_commutation_inductance.setValidator(QDoubleValidator())

        # set input masks and validators for switch parameters
        self.lineEdit_create_transistor_switch_t_j_max.setValidator(QDoubleValidator())
        self.lineEdit_create_transistor_switch_r_th_total.setValidator(QDoubleValidator())
        self.lineEdit_create_transistor_switch_c_th_total.setValidator(QDoubleValidator())
        self.lineEdit_create_transistor_switch_tau_total.setValidator(QDoubleValidator())
        self.lineEdit_create_transistor_switch_add_channel_data_t_j.setValidator(QDoubleValidator())
        self.lineEdit_create_transistor_switch_add_channel_data_v_g.setValidator(QDoubleValidator())
        self.lineEdit_create_transistor_switch_add_switching_losses_t_j.setValidator(QDoubleValidator())
        self.lineEdit_create_transistor_switch_add_switching_losses_v_g.setValidator(QDoubleValidator())
        self.lineEdit_create_transistor_switch_add_switching_losses_r_g_i_x.setValidator(QDoubleValidator())
        self.lineEdit_create_transistor_switch_add_switching_losses_v_supply.setValidator(QDoubleValidator())
        self.lineEdit_create_transistor_switch_add_gate_charge_i_channel.setValidator(QDoubleValidator())
        self.lineEdit_create_transistor_switch_add_gate_charge_t_j.setValidator(QDoubleValidator())
        self.lineEdit_create_transistor_switch_add_gate_charge_v_supply.setValidator(QDoubleValidator())
        self.lineEdit_create_transistor_switch_add_gate_charge_i_g.setValidator(QDoubleValidator())
        self.lineEdit_create_transistor_switch_add_r_on_i_channel.setValidator(QDoubleValidator())
        self.lineEdit_create_transistor_switch_add_r_on_v_g.setValidator(QDoubleValidator())
        self.lineEdit_create_transistor_switch_add_r_on_r_channel_nominal.setValidator(QDoubleValidator())

        self.lineEdit_create_transistor_switch_soa_t_pulse_time_pulse.setValidator(QDoubleValidator(0.0, 1000.0, 8))
        self.lineEdit_create_transistor_switch_soa_t_pulse_t_c.setValidator(QDoubleValidator(-300.0, 300.0, 2))

        # set input masks and validators for diode parameters
        self.lineEdit_create_transistor_diode_t_j_max.setValidator(QDoubleValidator())
        self.lineEdit_create_transistor_diode_r_th_total.setValidator(QDoubleValidator())
        self.lineEdit_create_transistor_diode_c_th_total.setValidator(QDoubleValidator())
        self.lineEdit_create_transistor_diode_tau_total.setValidator(QDoubleValidator())
        self.lineEdit_create_transistor_diode_add_channel_data_t_j.setValidator(QDoubleValidator())
        self.lineEdit_create_transistor_diode_add_channel_data_v_g.setValidator(QDoubleValidator())
        self.lineEdit_create_transistor_diode_add_switching_losses_t_j.setValidator(QDoubleValidator())
        self.lineEdit_create_transistor_diode_add_switching_losses_v_g.setValidator(QDoubleValidator())
        self.lineEdit_create_transistor_diode_add_switching_losses_r_g_i_x.setValidator(QDoubleValidator())
        self.lineEdit_create_transistor_diode_add_switching_losses_v_supply.setValidator(QDoubleValidator())
        self.lineEdit_create_transistor_diode_soa_t_pulse_time_pulse.setValidator(QDoubleValidator(0.0, 1000.0, 8))
        self.lineEdit_create_transistor_diode_soa_t_pulse_t_c.setValidator(QDoubleValidator(-300, 300, 2))

        # SEARCH DATABASE #

        # fill the comboBoxes
        self.comboBox_search_database_load_comparison_tools.addItems(["Transistor1", "Transistor2", "Transistor3"])
        self.comboBox_search_database_load_topology_calculator.addItems(["Transistor1", "Transistor2"])

        # connect the buttons to the functions
        self.button_search_database_load_exporting_tools.clicked.connect(
            self.load_from_search_database_into_exporting_tools)
        self.button_search_database_load_comparison_tools.clicked.connect(
            self.load_from_search_database_into_comparison_tools)
        self.button_search_database_load_topology_calculator.clicked.connect(
            self.load_from_search_database_into_topology_calculator)
        self.button_search_database_load_create_transistor.clicked.connect(
            self.load_from_search_database_into_create_transistor)
        self.button_search_database_reset_filters.clicked.connect(self.reset_filter_search_database)
        self.button_update_from_fileexchange.clicked.connect(self.update_database_from_fileexchange)

        # connect all checkBoxes(when state changed) and lineEdits(when text changed) to the functions to load data into the tableWidget
        self.checkBox_search_database_name.stateChanged.connect(self.search_database_load_data)
        self.checkBox_search_database_type.stateChanged.connect(self.search_database_load_data)
        self.checkBox_search_database_author.stateChanged.connect(self.search_database_load_data)
        self.checkBox_search_database_technology.stateChanged.connect(self.search_database_load_data)
        self.checkBox_search_database_template_version.stateChanged.connect(self.search_database_load_data)
        self.checkBox_search_database_template_date.stateChanged.connect(self.search_database_load_data)
        self.checkBox_search_database_creation_date.stateChanged.connect(self.search_database_load_data)
        self.checkBox_search_database_last_modified.stateChanged.connect(self.search_database_load_data)
        self.checkBox_search_database_comment.stateChanged.connect(self.search_database_load_data)
        self.checkBox_search_database_datasheet_hyperlink.stateChanged.connect(self.search_database_load_data)
        self.checkBox_search_database_datasheet_date.stateChanged.connect(self.search_database_load_data)
        self.checkBox_search_database_datasheet_version.stateChanged.connect(self.search_database_load_data)
        self.checkBox_search_database_housing_area.stateChanged.connect(self.search_database_load_data)
        self.checkBox_search_database_cooling_area.stateChanged.connect(self.search_database_load_data)
        self.checkBox_search_database_r_g_int.stateChanged.connect(self.search_database_load_data)
        self.checkBox_search_database_t_c_max.stateChanged.connect(self.search_database_load_data)
        self.checkBox_search_database_r_g_on_recommended.stateChanged.connect(self.search_database_load_data)
        self.checkBox_search_database_r_g_off_recommended.stateChanged.connect(self.search_database_load_data)
        self.checkBox_search_database_c_oss_fix.stateChanged.connect(self.search_database_load_data)
        self.checkBox_search_database_c_iss_fix.stateChanged.connect(self.search_database_load_data)
        self.checkBox_search_database_c_rss_fix.stateChanged.connect(self.search_database_load_data)
        self.checkBox_search_database_housing_type.stateChanged.connect(self.search_database_load_data)
        self.checkBox_search_database_manufacturer.stateChanged.connect(self.search_database_load_data)
        self.checkBox_search_database_r_th_cs.stateChanged.connect(self.search_database_load_data)
        self.checkBox_search_database_r_th_switch_cs.stateChanged.connect(self.search_database_load_data)
        self.checkBox_search_database_r_th_diode_cs.stateChanged.connect(self.search_database_load_data)
        self.checkBox_search_database_v_abs_max.stateChanged.connect(self.search_database_load_data)
        self.checkBox_search_database_i_abs_max.stateChanged.connect(self.search_database_load_data)
        self.checkBox_search_database_i_cont.stateChanged.connect(self.search_database_load_data)
        self.checkBox_search_database_switch_t_j_max.stateChanged.connect(self.search_database_load_data)
        self.checkBox_search_database_switch_comment.stateChanged.connect(self.search_database_load_data)
        self.checkBox_search_database_switch_manufacturer.stateChanged.connect(self.search_database_load_data)
        self.checkBox_search_database_switch_technology.stateChanged.connect(self.search_database_load_data)
        self.checkBox_search_database_diode_comment.stateChanged.connect(self.search_database_load_data)
        self.checkBox_search_database_diode_manufacturer.stateChanged.connect(self.search_database_load_data)
        self.checkBox_search_database_diode_technology.stateChanged.connect(self.search_database_load_data)
        self.checkBox_search_database_diode_t_j_max.stateChanged.connect(self.search_database_load_data)

        self.lineEdit_search_database_housing_area_min.textChanged.connect(self.search_database_load_data)
        self.lineEdit_search_database_cooling_area_min.textChanged.connect(self.search_database_load_data)
        self.lineEdit_search_database_r_g_int_min.textChanged.connect(self.search_database_load_data)
        self.lineEdit_search_database_t_c_max_min.textChanged.connect(self.search_database_load_data)
        self.lineEdit_search_database_r_g_on_recommended_min.textChanged.connect(self.search_database_load_data)
        self.lineEdit_search_database_r_g_off_recommended_min.textChanged.connect(self.search_database_load_data)
        self.lineEdit_search_database_c_oss_fix_min.textChanged.connect(self.search_database_load_data)
        self.lineEdit_search_database_c_iss_fix_min.textChanged.connect(self.search_database_load_data)
        self.lineEdit_search_database_c_rss_fix_min.textChanged.connect(self.search_database_load_data)
        self.lineEdit_search_database_r_th_cs_min.textChanged.connect(self.search_database_load_data)
        self.lineEdit_search_database_r_th_switch_cs_min.textChanged.connect(self.search_database_load_data)
        self.lineEdit_search_database_r_th_diode_cs_min.textChanged.connect(self.search_database_load_data)
        self.lineEdit_search_database_v_abs_max_min.textChanged.connect(self.search_database_load_data)
        self.lineEdit_search_database_i_abs_max_min.textChanged.connect(self.search_database_load_data)
        self.lineEdit_search_database_i_cont_min.textChanged.connect(self.search_database_load_data)
        self.lineEdit_search_database_switch_t_j_max_min.textChanged.connect(self.search_database_load_data)
        self.lineEdit_search_database_diode_t_j_max_min.textChanged.connect(self.search_database_load_data)

        self.lineEdit_search_database_housing_area_max.textChanged.connect(self.search_database_load_data)
        self.lineEdit_search_database_cooling_area_max.textChanged.connect(self.search_database_load_data)
        self.lineEdit_search_database_r_g_int_max.textChanged.connect(self.search_database_load_data)
        self.lineEdit_search_database_t_c_max_max.textChanged.connect(self.search_database_load_data)
        self.lineEdit_search_database_r_g_on_recommended_max.textChanged.connect(self.search_database_load_data)
        self.lineEdit_search_database_r_g_off_recommended_max.textChanged.connect(self.search_database_load_data)
        self.lineEdit_search_database_c_oss_fix_max.textChanged.connect(self.search_database_load_data)
        self.lineEdit_search_database_c_iss_fix_max.textChanged.connect(self.search_database_load_data)
        self.lineEdit_search_database_c_rss_fix_max.textChanged.connect(self.search_database_load_data)
        self.lineEdit_search_database_r_th_cs_max.textChanged.connect(self.search_database_load_data)
        self.lineEdit_search_database_r_th_switch_cs_max.textChanged.connect(self.search_database_load_data)
        self.lineEdit_search_database_r_th_diode_cs_max.textChanged.connect(self.search_database_load_data)
        self.lineEdit_search_database_v_abs_max_max.textChanged.connect(self.search_database_load_data)
        self.lineEdit_search_database_i_abs_max_max.textChanged.connect(self.search_database_load_data)
        self.lineEdit_search_database_i_cont_max.textChanged.connect(self.search_database_load_data)
        self.lineEdit_search_database_switch_t_j_max_max.textChanged.connect(self.search_database_load_data)
        self.lineEdit_search_database_diode_t_j_max_max.textChanged.connect(self.search_database_load_data)

        self.lineEdit_search_database_name.textChanged.connect(self.search_database_load_data)
        self.lineEdit_search_database_type.textChanged.connect(self.search_database_load_data)
        self.lineEdit_search_database_author.textChanged.connect(self.search_database_load_data)
        self.lineEdit_search_database_technology.textChanged.connect(self.search_database_load_data)
        self.lineEdit_search_database_template_version.textChanged.connect(self.search_database_load_data)
        self.lineEdit_search_database_template_date.textChanged.connect(self.search_database_load_data)
        self.lineEdit_search_database_creation_date.textChanged.connect(self.search_database_load_data)
        self.lineEdit_search_database_last_modified.textChanged.connect(self.search_database_load_data)
        self.lineEdit_search_database_comment.textChanged.connect(self.search_database_load_data)
        self.lineEdit_search_database_datasheet_hyperlink.textChanged.connect(self.search_database_load_data)
        self.lineEdit_search_database_datasheet_date.textChanged.connect(self.search_database_load_data)
        self.lineEdit_search_database_datasheet_version.textChanged.connect(self.search_database_load_data)
        self.lineEdit_search_database_housing_type.textChanged.connect(self.search_database_load_data)
        self.lineEdit_search_database_manufacturer.textChanged.connect(self.search_database_load_data)
        self.lineEdit_search_database_switch_comment.textChanged.connect(self.search_database_load_data)
        self.lineEdit_search_database_switch_manufacturer.textChanged.connect(self.search_database_load_data)
        self.lineEdit_search_database_switch_technology.textChanged.connect(self.search_database_load_data)
        self.lineEdit_search_database_diode_comment.textChanged.connect(self.search_database_load_data)
        self.lineEdit_search_database_diode_manufacturer.textChanged.connect(self.search_database_load_data)
        self.lineEdit_search_database_diode_technology.textChanged.connect(self.search_database_load_data)

        # load data into the tableWidget when starting the program
        self.search_database_load_data()
        # Search Database: set input masks and validators
        self.lineEdit_search_database_housing_area_min.setValidator(QDoubleValidator())
        self.lineEdit_search_database_housing_area_max.setValidator(QDoubleValidator())
        self.lineEdit_search_database_cooling_area_min.setValidator(QDoubleValidator())
        self.lineEdit_search_database_cooling_area_max.setValidator(QDoubleValidator())
        self.lineEdit_search_database_t_c_max_min.setValidator(QDoubleValidator())
        self.lineEdit_search_database_t_c_max_max.setValidator(QDoubleValidator())
        self.lineEdit_search_database_r_g_int_min.setValidator(QDoubleValidator())
        self.lineEdit_search_database_r_g_int_max.setValidator(QDoubleValidator())
        self.lineEdit_search_database_r_g_on_recommended_min.setValidator(QDoubleValidator())
        self.lineEdit_search_database_r_g_on_recommended_max.setValidator(QDoubleValidator())
        self.lineEdit_search_database_r_g_off_recommended_min.setValidator(QDoubleValidator())
        self.lineEdit_search_database_r_g_off_recommended_max.setValidator(QDoubleValidator())
        self.lineEdit_search_database_c_oss_fix_min.setValidator(QDoubleValidator())
        self.lineEdit_search_database_c_oss_fix_max.setValidator(QDoubleValidator())
        self.lineEdit_search_database_c_iss_fix_min.setValidator(QDoubleValidator())
        self.lineEdit_search_database_c_iss_fix_max.setValidator(QDoubleValidator())
        self.lineEdit_search_database_c_rss_fix_min.setValidator(QDoubleValidator())
        self.lineEdit_search_database_c_rss_fix_max.setValidator(QDoubleValidator())
        self.lineEdit_search_database_r_th_cs_min.setValidator(QDoubleValidator())
        self.lineEdit_search_database_r_th_cs_max.setValidator(QDoubleValidator())
        self.lineEdit_search_database_r_th_switch_cs_min.setValidator(QDoubleValidator())
        self.lineEdit_search_database_r_th_switch_cs_max.setValidator(QDoubleValidator())
        self.lineEdit_search_database_r_th_diode_cs_min.setValidator(QDoubleValidator())
        self.lineEdit_search_database_r_th_diode_cs_max.setValidator(QDoubleValidator())
        self.lineEdit_search_database_v_abs_max_min.setValidator(QDoubleValidator())
        self.lineEdit_search_database_v_abs_max_max.setValidator(QDoubleValidator())
        self.lineEdit_search_database_i_abs_max_min.setValidator(QDoubleValidator())
        self.lineEdit_search_database_i_abs_max_max.setValidator(QDoubleValidator())
        self.lineEdit_search_database_i_cont_min.setValidator(QDoubleValidator())
        self.lineEdit_search_database_i_cont_max.setValidator(QDoubleValidator())
        self.lineEdit_search_database_switch_t_j_max_min.setValidator(QDoubleValidator())
        self.lineEdit_search_database_switch_t_j_max_max.setValidator(QDoubleValidator())
        self.lineEdit_search_database_diode_t_j_max_min.setValidator(QDoubleValidator())
        self.lineEdit_search_database_diode_t_j_max_max.setValidator(QDoubleValidator())

    def closeEvent(self, event):
        """
        Run when window is closed and saves window size.

        :param event: event signal when window is closed
        :return:
        """
        size = self.size()
        self.resize(size)
        self.hide()
        self.move(1, 2)
        self.close()

    def __del__(self):
        """
        Print standard output in stdout-textEdit.

        :return: None
        """
        sys.stdout = sys.__stdout__


class CurveCheckerWindow(QMainWindow):
    """
    CurveCheckerWindow class which inherits from QMainWindow.

    Contains all the code and functions to implement all functionalities into the code generated by QTDesigner in CurveCheckerWindow.ui
    """

    def __init__(self):
        super(CurveCheckerWindow, self).__init__()
        uic.loadUi("CurveCheckerWindow.ui", self)

        self.setWindowIcon(QtGui.QIcon(resource_path("window_icon")))

        self.matplotlibwidget = MatplotlibWidget()
        self.matplotlibwidget.axis_cm.remove()

        self.checkBox_first_xy_to_00.stateChanged.connect(self.update_curve)
        self.checkBox_second_y_to_0.stateChanged.connect(self.update_curve)
        self.checkBox_first_x_to_0.stateChanged.connect(self.update_curve)
        self.checkBox_mirror_xy_data.stateChanged.connect(self.update_curve)
        self.radioButton_scale_linear.toggled.connect(self.update_curve)
        self.radioButton_scale_log_x.toggled.connect(self.update_curve)
        self.radioButton_scale_log_y.toggled.connect(self.update_curve)
        self.radioButton_scale_log_xy.toggled.connect(self.update_curve)

        self.button_save_curve.clicked.connect(self.save_curve)

    def save_curve(self):
        """
        Save curve to the corresponding comboBox and coverts the graph key to an array using the function tdb.csv2array().

        Then remove the file path key from the dict so that the dict can be used to create a transistor.

        :return: None
        """
        curve_title = self.matplotlibwidget.axis.get_title()

        if curve_title == "Switch Channel Curve":
            comboBox = MainWindow.comboBox_create_transistor_switch_added_curves_channel_data
        elif curve_title == "Switch Switching Losses Curve":
            comboBox = MainWindow.comboBox_create_transistor_switch_added_curves_switching_losses
        elif curve_title == "Switch Gate Charge Curve":
            comboBox = MainWindow.comboBox_create_transistor_switch_added_curves_gate_charge
        elif curve_title == "Switch On Resistance Curve":
            comboBox = MainWindow.comboBox_create_transistor_switch_added_curves_r_on
        elif curve_title == "Switch SOA Curve":
            comboBox = MainWindow.comboBox_create_transistor_switch_added_curves_soa_t_pulse
        elif curve_title == "Diode Channel Curve":
            comboBox = MainWindow.comboBox_create_transistor_diode_added_curves_channel_data
        elif curve_title == "Diode Reverse Recovery Losses Curve":
            comboBox = MainWindow.comboBox_create_transistor_diode_added_curves_switching_losses
        elif curve_title == "Diode SOA Curve":
            comboBox = MainWindow.comboBox_create_transistor_diode_added_curves_soa_t_pulse
        elif curve_title == "Switch T_Rthjc Curve":
            comboBox = MainWindow.comboBox_create_transistor_switch_added_curve_t_rthjc
        elif curve_title == "Diode T_Rthjc Curve":
            comboBox = MainWindow.comboBox_create_transistor_diode_added_curve_t_rthjc
        elif curve_title == "E_coss Curve":
            comboBox = MainWindow.comboBox_create_transistor_added_curve_v_ecoss
        elif curve_title == "C_iss_normal Curve":
            comboBox = MainWindow.comboBox_create_transistor_added_c_iss_normal
        elif curve_title == "C_iss_detail Curve":
            comboBox = MainWindow.comboBox_create_transistor_added_c_iss_detail
        elif curve_title == "C_oss_normal Curve":
            comboBox = MainWindow.comboBox_create_transistor_added_c_oss_normal
        elif curve_title == "C_oss_detail Curve":
            comboBox = MainWindow.comboBox_create_transistor_added_c_oss_detail
        elif curve_title == "C_rss_normal Curve":
            comboBox = MainWindow.comboBox_create_transistor_added_c_rss_normal
        elif curve_title == "C_rss_detail Curve":
            comboBox = MainWindow.comboBox_create_transistor_added_c_rss_detail

        data_dict = self.comboBox_data.itemData(self.comboBox_data.currentIndex())

        for key in data_dict.keys():
            if "graph" in key:
                data_dict[key] = csv2array(data_dict["path"],
                                           first_xy_to_00=self.checkBox_first_xy_to_00.isChecked(),
                                           second_y_to_0=self.checkBox_second_y_to_0.isChecked(),
                                           first_x_to_0=self.checkBox_first_x_to_0.isChecked(),
                                           mirror_xy_data=self.checkBox_mirror_xy_data.isChecked())

        data_dict.pop("path")

        comboBox.setItemData(comboBox.currentIndex(), data_dict)
        comboBox.setDisabled(False)

        self.close()

    def update_curve(self):
        """
        Change the curve when a CheckBox is checked in the CurveCheckerWindow using the function tdb.csv2array().

        :return: None
        """
        data_dict = self.comboBox_data.itemData(self.comboBox_data.currentIndex())
        graph = csv2array(data_dict["path"],
                          first_xy_to_00=self.checkBox_first_xy_to_00.isChecked(),
                          second_y_to_0=self.checkBox_second_y_to_0.isChecked(),
                          first_x_to_0=self.checkBox_first_x_to_0.isChecked(),
                          mirror_xy_data=self.checkBox_mirror_xy_data.isChecked())

        xlabel = self.matplotlibwidget.axis.get_xlabel()
        ylabel = self.matplotlibwidget.axis.get_ylabel()
        curve_title = self.matplotlibwidget.axis.get_title()
        curve_label = self.comboBox_data.currentText()
        self.matplotlibwidget.axis.clear()

        if self.radioButton_scale_log_xy.isChecked() is True:
            self.matplotlibwidget.axis.loglog(graph[0], graph[1], label=curve_label)
        elif self.radioButton_scale_linear.isChecked() is True:
            self.matplotlibwidget.axis.plot(graph[0], graph[1], label=curve_label)
        elif self.radioButton_scale_log_x.isChecked() is True:
            self.matplotlibwidget.axis.semilogx(graph[0], graph[1], label=curve_label)
        elif self.radioButton_scale_log_y.isChecked() is True:
            self.matplotlibwidget.axis.semilogy(graph[0], graph[1], label=curve_label)

        self.matplotlibwidget.axis.grid()
        self.matplotlibwidget.axis.set(xlabel=xlabel,
                                       ylabel=ylabel,
                                       title=curve_title)
        self.matplotlibwidget.axis.legend(fontsize=6)
        self.matplotlibwidget.figure.canvas.draw_idle()

        self.matplotlibwidget.cursor = Cursor(self.matplotlibwidget.axis, horizOn=True, vertOn=True, useblit=True,
                                              color="Green", linewidth=1)

    def run_curve_checker(self, comboBox, xlabel, ylabel, curve_title):
        """
        Run the CurveChecker with a given comboBox containing an added curve.

        :param comboBox: comboBox object that contains the added curve
        :param xlabel: xlabel for the added curve
        :param ylabel: ylabel for the added curve
        :param curve_title: curve_title for the added curve
        :return: None
        """
        try:
            self.layout = QVBoxLayout(self.widget_plot)
            self.layout.addWidget(self.matplotlibwidget)

            data_dict = comboBox.itemData(comboBox.currentIndex())
            curve_label = comboBox.currentText()

            self.comboBox_data.addItem(curve_label, data_dict)

            self.comboBox_data.setDisabled(True)

            self.matplotlibwidget.axis.set(xlabel=xlabel,
                                           ylabel=ylabel,
                                           title=curve_title)

            self.radioButton_scale_linear.setChecked(True)

            self.update_curve()

            self.show()
        except:
            comboBox.removeItem(comboBox.currentIndex())
            MainWindow.show_popup_message("Selected file is not valid!")

    def closeEvent(self, event):
        """
        Save curve and gets window size settings when window is closed.

        :param event: event signal when window is closed
        :return: None
        """
        self.save_curve()


class InformationWindow(QMainWindow):
    """
    InformationWindow class which inherits from QMainWindow.

    Contains all the code and functions to implement all functionalities into the code generated by QTDesigner in InformationWindow.ui
    """

    def __init__(self):
        super(InformationWindow, self).__init__()
        uic.loadUi("InformationWindow.ui", self)
        self.setWindowIcon(QtGui.QIcon("window_icon"))

        self.button_yes.clicked.connect(self.button_yes_pressed)
        self.button_cancel.clicked.connect(self.button_cancel_pressed)

    def button_yes_pressed(self):
        """
        Run the function to overwrite transistor, when the button "Yes" is pressed.

        :return: None
        """
        MainWindow.overwrite_transistor()
        self.close()

    def button_cancel_pressed(self):
        """
        Close the information window the the button "Cancel" is pressed.

        :return: None
        """
        MainWindow.button_create_transistor_create.setDisabled(True)

        self.close()

    def run_information_window(self):
        """
        Run the information window.

        :return: None
        """
        dict = MainWindow.create_transistor()
        transistor = dict["transistor"]

        self.label_text.setText(
            f"<b>{transistor.name}</b> already exists in the Local Database! Do you want to overwrite the existing transistor?")

        self.show()


if __name__ == "__main__":
    import sys

    app = QApplication(sys.argv)
    MainWindow = MainWindow()
    MainWindow.show()
    sys.exit(app.exec_())
