# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for the TDB backend (headless FastAPI REST API)."""

block_cipher = None

a = Analysis(
    ['../transistordatabase/scripts/tdb_backend.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('../transistordatabase/database', 'transistordatabase/database'),
    ],
    hiddenimports=[
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'fastapi',
        'fastapi.middleware.cors',
        'fastapi.staticfiles',
        'starlette',
        'starlette.middleware',
        'starlette.middleware.cors',
        'anyio',
        'anyio._backends._asyncio',
        'transistordatabase',
        'transistordatabase.core',
        'transistordatabase.core.models',
        'transistordatabase.core.repository',
        'transistordatabase.core.adapters',
        'transistordatabase.core.services',
        'transistordatabase.backend',
        'transistordatabase.backend.concrete_services',
        'transistordatabase.gui_web.backend.main',
        'transistordatabase.gui_web.backend.schemas',
        'transistordatabase.gui_web.backend.topology_service',
        'transistordatabase.core.pair_repository',
        'multipart',
        'email.mime',
        'email.mime.multipart',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'PyQt5',
        'PyQtWebEngine',
        'tkinter',
        'matplotlib.backends._backend_tk',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='tdb-backend',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
